config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'users/index'
  end

  namespace :admins do
    get 'offers/index'
  end

  namespace :admins do
    get 'requests/index'
  end

  namespace :admins do
    get 'dashboard/index'
  end

  devise_for :admins
  devise_for :users

  resources :requests
  resources :offers

  resources :users do
    get "liftsSharedAsDriver",    to: "users#liftsSharedAsDriver"
  	member do
  		get :requests
  		get :offers
  	end
  end
  root "requests#index"

#####################################################################################
  namespace :admins do
    root to: "dashboard#index"
    get "requests", to: "requests#index" 
    get "requests/:id", to: "requests#show", as: 'request'  
    get "offers", to: "offers#index"
    get "offers/:id", to: "offers#show", as: 'offer'
    get "users", to: "users#index"
    get "users/:id", to: "users#show", as: 'user'  
  end
########################################################################################
end

app/models/offer.rb
class Offer < ApplicationRecord
	belongs_to :user
	scope :last_x_days, -> (x) { where(created_at: x.days.ago..Time.zone.now) }
end

app/controllers/admins/offers_controller.rb
class Admins::OffersController < ApplicationController
 
  before_action :find_offer, only: [:show]

  def index
  	@search = Offer.search(params[:q])
	@offers = @search.result.order("created_at DESC").page(params[:page]).per(20) #display 20 per page
  	#@offers = Offer.order("created_at DESC").page(params[:page])
  end

  def find_offer
	@offer = Offer.find(params[:id])
  end
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	before_action :find_offer, only: [:show, :edit, :update, :destroy]
	load_and_authorize_resource
	

	def index
		#show offers where time of departure is not in the past
		@offers = Offer.where('time > ?', DateTime.now).order("created_at DESC")
	end

	def new
		@offer = current_user.offers.build
	end

	def create
		@offer = current_user.offers.build(offer_params)

		if @offer.save
			redirect_to @offer, notice: "succesfully created new post"
		else
			render 'new'
		end
	end

	def edit

	end

	def destroy
		@offer.destroy
		if user_signed_in?
			redirect_to root_path
		elsif admin_signed_in?
			redirect_to admins_offers_path
		end		
	end

	def show
		gon.offer = @offer
	end

	def update
		if @offer.update(offer_params)
			redirect_to @offer, notice: "post succesfully updated"
		else
			render 'edit'
		end
	end

	private

	def offer_params
		params.require(:offer).permit(:destination, :departure, :time, :seats, :passengerid, :accepted, :desc)
	end

	def find_offer
		@offer = Offer.find(params[:id])
	end


end

app/helpers/admins/offers_helper.rb
module Admins::OffersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/admins/offers/index.html.haml
-if admin_signed_in?

	%h1 Offers
	.row-fluid
		.block-body
			%BR
			%table.table.table-striped{width: '100%'}
				%thead
					%tr.medium
						%th Offer ID
						%th User ID
						%th Created At
						%th Departure
						%th Destination
						%th Time
						%th Accepted
				%tbody

					= search_form_for @search, url: admins_offers_path do |f|
						%td= f.text_field :id_eq, class: "form-control input-sm", size: 4
						%td= f.text_field :user_id_eq, class: "form-control input-sm", size: 4
						%td
						%td= f.text_field :departure_cont, class: "form-control input-sm", size: 4
						%td= f.text_field :destination_cont, class: "form-control input-sm", size: 4
						%td
						%td= f.text_field :accepted_eq, class: "form-control input-sm", size: 4

						%td.actions
							%button.btn.btn-default{:type => "submit"}
								%i.glyphicon.glyphicon-search
							.btn.btn-default= link_to content_tag(:i, "", class: "glyphicon glyphicon-remove"),admins_offers_path , class:"cancel-button"

					-@offers.each do |offer|
						%tr.medium
							%td= link_to offer.id, admins_offer_path(offer.id)
							%td= offer.user_id	
							%td= offer.created_at
							%td= offer.departure 
							%td= offer.destination    
							%td= offer.time 
							%td= offer.accepted 
	   					
	=paginate @offers
-else
	%h1 You shall not pass

app/views/admins/offers/show.html.haml
-if admin_signed_in?

	%h2 Offer 

	.row
		
		%dl.dl-horizontal
			%dt= t 'Offer ID', :default => "Offer ID:" 
			%dd= @offer.id
		%dl.dl-horizontal
			%dt= t 'User ID', :default => "User ID:" 
			%dd= @offer.user_id		
		%dl.dl-horizontal
			%dt= t 'Created At', :default => "Created At:" 
			%dd= @offer.created_at
		%dl.dl-horizontal
			%dt= t 'Departure', :default => "Departure:" 
			%dd= @offer.departure
		%dl.dl-horizontal
			%dt= t 'Destination', :default => "Destination:" 
			%dd= @offer.destination
		%dl.dl-horizontal
			%dt= t 'Estimated Time of Departure', :default => "ETD:" 
			%dd= @offer.time
		%dl.dl-horizontal
			%dt= t 'Accepted', :default => "Accepted:" 
			%dd= @offer.accepted
		%dl.dl-horizontal
			%dt= t 'Seats', :default => "Seats:" 
			%dd= @offer.seats
		%dl.dl-horizontal
			%dt= t 'Description', :default => "Description:" 
			%dd= @offer.desc				
	%br/
	=link_to "Delete", offer_path, method: :delete, data:{confirm: "Are you sure?"}