config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'users/index'
  end

  namespace :admins do
    get 'offers/index'
  end

  namespace :admins do
    get 'requests/index'
  end

  namespace :admins do
    get 'dashboard/index'
  end

  devise_for :admins
  devise_for :users

  resources :requests
  resources :offers

  resources :users do
    get "liftsSharedAsDriver",    to: "users#liftsSharedAsDriver"
  	member do
  		get :requests
  		get :offers
  	end
  end
  root "requests#index"

#####################################################################################
  namespace :admins do
    root to: "dashboard#index"
    get "requests", to: "requests#index" 
    get "requests/:id", to: "requests#show", as: 'request'  
    get "offers", to: "offers#index"
    get "offers/:id", to: "offers#show", as: 'offer'
    get "users", to: "users#index"
    get "users/:id", to: "users#show", as: 'user'  
  end
########################################################################################
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :requests
  has_many :offers

  mount_uploader :avatar, AvatarUploader

  scope :last_x_days, -> (x) { where(created_at: x.days.ago..Time.zone.now) }

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  
	before_action :find_user, only: [:show]

	def index
		@search = User.search(params[:q])
		@users = @search.result.page(params[:page]).per(20) #display 20 per page
		#@requests = Request.order("created_at DESC").page(params[:page])
	end

	def find_user
		@user = User.find(params[:id])
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy, :liftsSharedAsDriver]

  # GET /users
  # GET /users.json
  def index
    @users = User.all   
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    @requests = @user.requests
    @other_requests = Request.where(driverid: @user.id).order("created_at DESC")
    
    @offers = @user.offers
    @other_offers = Offer.where(passengerid: @user.id).order("created_at DESC")
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def post
    @user = User.find(params[:id])
    @requests = @user.requests
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/index.html.haml
%h1= link_to "Users", admins_users_index_path

.row-fluid
	.block-body
		%BR
		%table.table.table-striped{width: '100%'}
			%thead
				%tr.medium
					%th User ID
					%th First Name
					%th Last Name
					%th Email
					%th Gender
			%tbody
				= search_form_for @search, url: admins_users_index_path do |f|
					%td= f.text_field :id_eq, class: "form-control input-sm", size: 4
					%td= f.text_field :fname_cont, class: "form-control input-sm", size: 4
					%td= f.text_field :lname_cont, class: "form-control input-sm", size: 4
					%td= f.text_field :email_cont, class: "form-control input-sm", size: 4
					%td= f.text_field :gender_eq, class: "form-control input-sm", size: 4
					
					%td.actions
						%button.btn.btn-default{:type => "submit"}
							%i.glyphicon.glyphicon-search
						.btn.btn-default= link_to content_tag(:i, "", class: "glyphicon glyphicon-remove"),admins_users_index_path , class:"cancel-button"

				-@users.each do |user|
					%tr.medium
						%td= link_to user.id, admins_user_path(user.id)
						%td= user.fname	
						%td= user.lname
						%td= user.email 
						%td= user.gender    
=paginate @users

app/views/admins/users/show.html.haml
%h2 User

.row
	
	%dl.dl-horizontal
		%dt= t 'User ID', :default => "User ID:" 
		%dd= @user.id	
	%dl.dl-horizontal
		%dt= t 'First Name', :default => "Last Name:" 
		%dd= @user.fname
	%dl.dl-horizontal
		%dt= t 'Last Name', :default => "Last Name:" 
		%dd= @user.lname
	%dl.dl-horizontal
		%dt= t 'Email', :default => "Email:" 
		%dd= @user.email
	%dl.dl-horizontal
		%dt= t 'Gender', :default => "Gender:" 
		%dd= @user.gender
	%dl.dl-horizontal
		%dt= t 'Last signed in', :default => "Last signed in:" 
		%dd= @user.last_sign_in_at		

=link_to "Delete", admins_users_index_path, method: :delete, data:{confirm: "Are you sure?"}