config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'users/index'
  end

  namespace :admins do
    get 'offers/index'
  end

  namespace :admins do
    get 'requests/index'
  end

  namespace :admins do
    get 'dashboard/index'
  end

  devise_for :admins
  devise_for :users

  resources :requests
  resources :offers

  resources :users do
    get "liftsSharedAsDriver",    to: "users#liftsSharedAsDriver"
  	member do
  		get :requests
  		get :offers
  	end
  end
  root "requests#index"

#####################################################################################
  namespace :admins do
    root to: "dashboard#index"
    get "requests", to: "requests#index" 
    get "requests/:id", to: "requests#show", as: 'request'  
    get "offers", to: "offers#index"
    get "offers/:id", to: "offers#show", as: 'offer'
    get "users", to: "users#index"
    get "users/:id", to: "users#show", as: 'user'  
  end
########################################################################################
end

app/models/request.rb
class Request < ApplicationRecord

	belongs_to :user
	validates :destination, :departure, :time, :presence => true
	scope :last_x_days, -> (x) { where(created_at: x.days.ago..Time.zone.now) }	
end

app/controllers/admins/requests_controller.rb
class Admins::RequestsController < ApplicationController
	before_action :find_request, only: [:show]

	def index
		@search = Request.search(params[:q])
		@requests = @search.result.order("created_at DESC").page(params[:page]).per(20) #display 20 per page
		#@requests = Request.order("created_at DESC").page(params[:page])
	end

	def find_request
		@request = Request.find(params[:id])
	end


	
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :find_request, only: [:show, :edit, :update, :destroy]
	load_and_authorize_resource
	
	

	def index
		#Only show requests that have not been accepted AND time of departure is  not before the current date
		@requests = Request.where(accepted: 'f').where('time > ?', DateTime.now).order("created_at DESC")
	end





	def new
		@request = current_user.requests.build
	end

	def create
		@request = current_user.requests.build(request_params)

		if @request.save
			redirect_to @request, notice: "succesfully created new post"
		else
			render 'new'
		end
	end


	def edit

	end

	def destroy
		@request.destroy
		if user_signed_in?
			redirect_to root_path
		elsif admin_signed_in?
			redirect_to admins_requests_path
		end			
	end

	def show
		gon.request = @request
	end

	def update
		if @request.update(request_params)
			redirect_to @request, notice: "post succesfully updated"
		else
			render 'edit'
		end
	end

	

	private

	def request_params
		params.require(:request).permit(:destination, :departure, :time, :driverid, :accepted, :desc)
	end

	def find_request
		@request = Request.find(params[:id])
	end

end

app/helpers/admins/requests_helper.rb
module Admins::RequestsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_accepted.html.haml
%h3 A user has already offered this person a lift

app/views/requests/_acceptedByUser.html.haml
%h3 You have succesfully offered this user a lift.

app/views/requests/_form.html.erb
<%= simple_form_for @request, html: { multipart: true } do |f| %>
  <% if @request.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@request.errors.count, "error") %>
        prevented this post from saving
      </h2>
      <ul>
        <% @request.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

<%= render 'map'%>


  <div class="form-group">
    <div class="box panel panel-default new">
      <div id="hide">
        <%= f.input :departure, input_html: {class: 'form-control', id: "departure"} %>
        <h4>to</h4>
        <%= f.input :destination, input_html: { class: 'form-control', id: "destination" } %>
        <%= f.input :desc %>
      </div>  
      <%= f.input :time %>
    </div>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/requests/_map.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqnbDDZdGNHuoFZk6LM3Jwq2JE8iVv7OA&libraries=places&callback=initMap"
        async defer></script>

<input id="origin-input" class="controls" type="text"
        placeholder="Departure">

    <input id="destination-input" class="controls" type="text"
        placeholder="Destination">

    <div id="mode-selector" class="controls">
     
      <input type="radio" name="type" id="changemode-driving" checked="checked">
      <label for="changemode-driving">Driving</label>
    </div>
<div id="map"></div>

<script type="text/javascript">
  // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">



      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          mapTypeControl: false,
          center: {lat: 54.602724, lng:-5.929291},
          zoom: 13
        });

        new AutocompleteDirectionsHandler(map);
      }

       /**
        * @constructor
       */
      function AutocompleteDirectionsHandler(map) {
        this.map = map;
        this.originPlaceId = null;
        this.destinationPlaceId = null;
        this.travelMode = 'WALKING';
        var originInput = document.getElementById('origin-input');
        var destinationInput = document.getElementById('destination-input');
        var modeSelector = document.getElementById('mode-selector');
        this.directionsService = new google.maps.DirectionsService;
        this.directionsDisplay = new google.maps.DirectionsRenderer;
        this.directionsDisplay.setMap(map);

        var originAutocomplete = new google.maps.places.Autocomplete(
            originInput, {placeIdOnly: true});
        var destinationAutocomplete = new google.maps.places.Autocomplete(
            destinationInput, {placeIdOnly: true});

        // this.setupClickListener('changemode-walking', 'WALKING');
        // this.setupClickListener('changemode-transit', 'TRANSIT');
        this.setupClickListener('changemode-driving', 'DRIVING');

        this.setupPlaceChangedListener(originAutocomplete, 'ORIG');
        this.setupPlaceChangedListener(destinationAutocomplete, 'DEST');

        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(originInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(destinationInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(modeSelector);
      }

      // Sets a listener on a radio button to change the filter type on Places
      // Autocomplete.
      AutocompleteDirectionsHandler.prototype.setupClickListener = function(id, mode) {
        var radioButton = document.getElementById(id);
        var me = this;
        radioButton.addEventListener('click', function() {
          me.travelMode = mode;
          me.route();
        });
      };

      AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(autocomplete, mode) {
        var me = this;
        autocomplete.bindTo('bounds', this.map);
        autocomplete.addListener('place_changed', function() {
          var place = autocomplete.getPlace();

        var start = document.getElementById("origin-input");
        $("#departure").val(start.value);

        var end = document.getElementById("destination-input");
        $("#destination").val(end.value);
        

            if (!place.place_id) {
            window.alert("Please select an option from the dropdown list.");
            return;
          }
          if (mode === 'ORIG') {
            me.originPlaceId = place.place_id;
          } else {
            me.destinationPlaceId = place.place_id;
          }
          me.route();
        });

      };

      AutocompleteDirectionsHandler.prototype.route = function() {
        if (!this.originPlaceId || !this.destinationPlaceId) {
          return;
        }
        var me = this;

        this.directionsService.route({
          origin: {'placeId': this.originPlaceId},
          destination: {'placeId': this.destinationPlaceId},
          travelMode: this.travelMode
        }, function(response, status) {
          if (status === 'OK') {
            me.directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      };


</script>

app/views/requests/_offer.html.haml
%h3= link_to "Offer this person a lift", 
          request_path(@request, 
                    :request => { :driverid => current_user.id, :accepted => 't'}),
          :method => :put, 
          :confirm => "Are you sure?"
          

app/views/requests/_route.html.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyDqnbDDZdGNHuoFZk6LM3Jwq2JE8iVv7OA&libraries=places"}

#map-canvas

:javascript
  
  function initMap() {   
    mapOptions = {
        zoom: 7,
    }
    var geocoder = new google.maps.Geocoder();
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions)


    // Instantiate a directions service.
    directionsService = new google.maps.DirectionsService,
    directionsDisplay = new google.maps.DirectionsRenderer({
        map: map
    })
    
    // get route from A to B
    // calculateAndDisplayRoute(directionsService, directionsDisplay, pointA, pointB);
    geocodeAddress(geocoder, map, directionsService, directionsDisplay);
  }

  //get lat long
  var test1;
  var test2;
  function geocodeAddress(geocoder, resultsMap, directionsService, directionsDisplay) {

    var depart = gon.request.departure
    geocoder.geocode({'address': depart}, function(results, status) { 
      if (status === 'OK') {
        test1 = results[0].geometry.location
        var markerA = new google.maps.Marker({
          title: "point A",
          label: "A",
          map: resultsMap,
          position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }

    });

    var dest = gon.request.destination
    geocoder.geocode({'address': dest}, function(results, status) {
      if (status === 'OK') {
        test2 = results[0].geometry.location
        var markerB = new google.maps.Marker({
          title: "point B",
          label: "B",
          map: resultsMap,
          position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }

      calculateAndDisplayRoute(directionsService, directionsDisplay, test1, test2);
    });

  }



  function calculateAndDisplayRoute(directionsService, directionsDisplay, test) {
      directionsService.route({
          origin: test1,
          destination: test2,
          avoidTolls: true,
          avoidHighways: false,
          travelMode: google.maps.TravelMode.DRIVING
      }, function (response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
              directionsDisplay.setDirections(response);
          } else {
              window.alert('Directions request failed due to ' + status);
          }
      });
  }

  initMap();


      

 

app/views/requests/edit.html.haml
- if current_user.id == @request.user_id

	%h1 Edit Form

	=render 'form'

	=link_to "Cancel", request_path
-else
	%h1 You shall not pass	

app/views/requests/index.html.haml
/check if user is admin 


%h4 Most recent lift request:

-@requests.each do |request|

	.container
		.box.panel.panel-default 
			%h3= link_to request.departure, request
			to
			%h3= link_to request.destination, request
			%br/
			=request.time.strftime("%dth %B,  %H:%M")
			%br/
			Posted by:
			=link_to "#{request.user.fname} #{request.user.lname}", user_path(request.user_id)
			.avatar
				=image_tag request.user.avatar.url.to_s

app/views/requests/new.html.haml
%h1 Request a lift
=render 'form'

app/views/requests/show.html.haml
-if @request.driverid.blank? && user_signed_in?	&& current_user != @request.user 
	=render 'offer'
-elsif current_user == @request.driverid
	=render 'acceptedByUser'
-elsif @request.driverid.blank? && current_user == @request.user  	

-else	
	=render 'accepted'	
%br/

=render 'route' 

.container
	%h3#depart=@request.departure 
	to
	%h3#arrive=@request.destination
	%br/
	=@request.time.strftime("%dth %B,  %H:%M")
	%br/
	=@request.desc
	%br/
	Submitted by 
	=link_to "#{@request.user.fname} #{@request.user.lname}", user_path(@request.user_id)
	%br/
	- if @request.driverid
		Accepted by 
		=link_to (@request.driverid), user_path(@request.driverid)
	%br/
	
	=@request.user.gender
	%br/

=link_to "Home", root_path 
=if current_user.id == @request.user_id
	=link_to "Edit", edit_request_path
	=link_to "Delete", request_path, method: :delete, data:{confirm: "Are you sure?"}


:javascript
	$( document ).ready(function() {
		var daddress = ($( "h3#depart" ).html());
		var res = daddress.split(",");
		$("#depart").html(res[0] + ", " + res[1]);

		var aaddress = ($( "h3#arrive" ).html());
		var res = aaddress.split(",");
		$("#arrive").html(res[0] + ", " + res[1]);
	});